### ISSUE TITLE
Making HCF Denizen compatible

### ISSUE THREAD

**Issue by Alphatrooper** [DenizenScript/Depenizen-For-Bukkit#114]
Possible to make plugin such as HCFactions or HCFCore compatible with denizen? I need to make a sidebar with the DTR from factions but there is no way for me to get that information from that plugin

Not sure how hard it is but if its possible, cheers.
Preferably 1.8 Denizen

tags such as
hcfactions.faction.dtr
hcfactions.faction.totaldtr
hcfactions.faction.home

**Comment by Fortifier42** [comment]
Could you by any chance post a link to the place you got your version of HCFactions/HCFCore, please?

**Comment by Morphan1** [comment]
This is not reasonably possible due to the developers making the mistake of not only using the same internal name for the plugin (Factions) but also keeping the same packages, which causes huge amounts of conflict while trying to support both Factions and HCFactions. Your best bet would be to ask the HCFactions to do something about this, such as possibly [adding a placeholder](https://www.spigotmc.org/resources/placeholderapi.6245/) which you could then use Denizen to access via the new `<placeholder[placeholder_here]>` tag.
