### ISSUE TITLE
Bungee support

### ISSUE THREAD

**Issue by mcmonkey4eva** [DenizenScript/Depenizen-For-Bukkit#33]
sending messages across servers- see https://github.com/DenizenScript/Denizen-For-Bukkit/issues/864

**Comment by Morphan1** [comment]
Sorry for how long this has taken, but this project is finally underway...
I've added a config.yml for Depenizen specifically for connecting to a Socket hosted by the <a href="https://github.com/DenizenScript/Depenizen-For-Bungee/">new Bungee-side plugin</a>

This allows your Bukkit servers and your BungeeCord server to communicate without the need for online players. This is useful for things such as handling Bungee events (like a player connecting) in Denizen scripts.

However, although recommended, the socket connection will not be required if you don't care that there has to be a player online on each server you want to communicate with.

As of right now, all that's set up is a simple connection, and no real useful data can be sent between Bukkit and Bungee yet. I'll work on that tonight - probably in the form of a command... If anyone has any ideas for syntax for such a command, let me know. Otherwise, I'll just add whatever I feel is necessary

**Comment by mcmonkey4eva** [comment]
`- bungee <server or 'all'> <command>`
EG
`- bungee Hub "run MyScript %local server parses this def% <hub parses this tag>"`

**Comment by Morphan1** [comment]
Hmm...  Why limit it to a single command? Would it be better to make it braced? That would allow you to be able to send entire sections at once, and have more option
```
- bungee Hub {
  - run MyScript 
  - run UnrelatedOtherScript 
  - announce "Ya dun did stuff!"
  }

**Comment by mcmonkey4eva** [comment]
Great idea!

**Comment by mcmonkey4eva** [comment]
Oh, and make sure it transmits queue.definitions if you do it that way.

**Comment by AnthonyAMC** [comment]
Bungee command script containers.

**Comment by Morphan1** [comment]
...What? What would be the use for such a thing?

**Comment by AnthonyAMC** [comment]
To do exactly what you said in the braced commands?
